# =============================================================================
# Arche Engine Auto-Loader Generator (Relative to Source)
# =============================================================================
# "ARCHE_REGISTER_SYSTEM" または "ARCHE_COMPONENT" マクロが含まれている
# ヘッダーファイルのみを抽出し、Loader.h に自動登録します。
# パスは "Source" フォルダを基準とした相対パスになります。
# =============================================================================

$ScriptDir = $PSScriptRoot
$ProjectRoot = (Get-Item "$ScriptDir\..").FullName
# インクルードの基準となる Source フォルダのパスを取得
$SourceDir = Join-Path $ProjectRoot "Source"

Write-Host "Project Root: $ProjectRoot"
Write-Host "Include Base: $SourceDir"

# --- 設定関数 ---
function Generate-Loader ($scanRelPath, $outputRelPath, $namespace) {
    Write-Host "Scanning $namespace..."
    
    $targetDir = Join-Path $ProjectRoot $scanRelPath
    $outputFile = Join-Path $ProjectRoot $outputRelPath

    # ヘッダーを検索
    $headers = Get-ChildItem -Path $targetDir -Recurse -Filter *.h | Where-Object { 
        $_.Name -ne "GameLoader.h" -and $_.Name -ne "EngineLoader.h" -and 
        (Select-String -Path $_.FullName -Pattern "ARCHE_REGISTER_|ARCHE_COMPONENT" -Quiet)
    }

    $content = "#pragma once`n"
    $content += "// =================================================================`n"
    $content += "// AUTO-GENERATED BY POWERSHELL. DO NOT EDIT.`n"
    $content += "// Namespace: $namespace`n"
    $content += "// =================================================================`n`n"

    foreach ($file in $headers) {
        $fullPath = $file.FullName
        
        # Sourceディレクトリからの相対パスを計算
        if ($fullPath.StartsWith($SourceDir)) {
            $relPath = $fullPath.Substring($SourceDir.Length)
        } else {
            # 万が一Source外の場合はProjectRootから計算（保険）
            $relPath = $fullPath.Substring($ProjectRoot.Length)
        }
        
        # 先頭の "\" や "/" を削除
        if ($relPath.StartsWith("\") -or $relPath.StartsWith("/")) {
            $relPath = $relPath.Substring(1)
        }
        
        # バックスラッシュをスラッシュに置換
        $relPath = $relPath.Replace("\", "/") 
        
        $content += "#include `"$relPath`"`n"
    }

    Set-Content -Path $outputFile -Value $content -Encoding UTF8
    Write-Host "Updated: $outputFile"
}

# --- 実行 ---

# 1. Engine側の生成
Generate-Loader "Source\Engine\Scene" "Source\Engine\EngineLoader.h" "Engine"

# 2. Sandbox(Game)側の生成
Generate-Loader "Source\Sandbox" "Source\Sandbox\GameLoader.h" "Sandbox"