# ▼▼▼ 重要: これを必ずファイルの先頭（コメントより前でも可）に書いてください ▼▼▼
param(
    [string]$Target = "All"
)
# ▲▲▲ ここまで ▲▲▲

# =============================================================================
# Arche Engine Auto-Loader Generator (Relative to Source)
# =============================================================================
# "ARCHE_REGISTER_SYSTEM" または "ARCHE_COMPONENT" マクロが含まれている
# ヘッダーファイルのみを抽出し、Loader.h に自動登録します。
# パスは "Source" フォルダを基準とした相対パスになります。
# =============================================================================

$ScriptDir = $PSScriptRoot
$ProjectRoot = (Get-Item "$ScriptDir\..").FullName
$SourceDir = Join-Path $ProjectRoot "Source"

# --- 設定関数 ---
function Generate-Loader ($scanRelPath, $outputRelPath, $namespace) {
    Write-Host "Scanning $namespace..."
    
    $targetDir = Join-Path $ProjectRoot $scanRelPath
    $outputFile = Join-Path $ProjectRoot $outputRelPath

    # ヘッダーを検索
    $headers = Get-ChildItem -Path $targetDir -Recurse -Filter *.h | Where-Object { 
        $_.Name -ne "GameLoader.h" -and $_.Name -ne "EngineLoader.h" -and 
        (Select-String -Path $_.FullName -Pattern "ARCHE_REGISTER_|ARCHE_COMPONENT" -Quiet)
    }

    $content = "#pragma once`n"
    $content += "// =================================================================`n"
    $content += "// AUTO-GENERATED BY POWERSHELL. DO NOT EDIT.`n"
    $content += "// Namespace: $namespace`n"
    $content += "// =================================================================`n`n"

    foreach ($file in $headers) {
        $fullPath = $file.FullName
        
        # Sourceディレクトリからの相対パスを計算
        if ($fullPath.StartsWith($SourceDir)) {
            $relPath = $fullPath.Substring($SourceDir.Length)
        } else {
            $relPath = $fullPath.Substring($ProjectRoot.Length)
        }
        
        # パス区切り文字の調整
        if ($relPath.StartsWith("\") -or $relPath.StartsWith("/")) {
            $relPath = $relPath.Substring(1)
        }
        $relPath = $relPath.Replace("\", "/") 
        
        $content += "#include `"$relPath`"`n"
    }

    # 変更がある場合のみ書き込む（無限ビルド防止）
    $needsWrite = $true
    if (Test-Path $outputFile) {
        $currentContent = Get-Content $outputFile -Raw -Encoding UTF8
        if ($currentContent -eq $content) {
            $needsWrite = $false
            Write-Host "No changes detected for $outputFile. Skipping write."
        }
    }

    if ($needsWrite) {
        Set-Content -Path $outputFile -Value $content -Encoding UTF8
        Write-Host "Updated: $outputFile"
    }
}

# --- 実行 ---

# Engine側: Targetが "Engine" または "All" の時だけ実行
if ($Target -eq "Engine" -or $Target -eq "All") {
    Generate-Loader "Source\Engine\Scene" "Source\Engine\EngineLoader.h" "Engine"
}

# Sandbox側: Targetが "Sandbox" または "All" の時だけ実行
if ($Target -eq "Sandbox" -or $Target -eq "All") {
    Generate-Loader "Source\Sandbox" "Source\Sandbox\GameLoader.h" "Sandbox"
}